# source ~/koskidex-p4/env-app.sh, poi php artisan ... da Documentale/apps/laravel
export DB_HOST=127.0.0.1 DB_PORT=33061 DB_DATABASE=albo DB_USERNAME=root DB_PASSWORD=root TELESCOPE_ENABLED=false
export SEARCH_BACKEND=koskidex KOSKIDEX_HOST=http://localhost:7717 KOSKIDEX_TIMEOUT=1800
export KOSKIDEX_PROFILO=consigliata
export KOSKIDEX_NORMALIZE_DATES=true KOSKIDEX_NORMALIZE_AMOUNTS=true KOSKIDEX_TYPOS_ON_AMOUNTS=false
export KOSKIDEX_SCORING=bm25 KOSKIDEX_STABLE_TERM_ORDER=true
export KOSKIDEX_EMBEDDER_MODEL=bge-m3 KOSKIDEX_HYBRID_MODE=union KOSKIDEX_VECTOR_WEIGHT=10
